ALTER TABLE users
ADD COLUMN IF NOT EXISTS email VARCHAR(150) DEFAULT NULL AFTER first_name,
ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) DEFAULT NULL AFTER phone;

ALTER TABLE users
ADD UNIQUE KEY IF NOT EXISTS email (email);
